### ISSUE TITLE
Printing size_t correctly

### ISSUE THREAD

**Issue by UnitedMarsupials** [dropbox/lepton#10]
Throughout the code variables of type `size_t` are printed as `long` (`%ld`). This is incorrect in two ways:

- `long` is signed, whereas `size_t` is not
- `long` may not be the same width as `size_t` -- in particular, on i386 (32-bit) systems `long` is usually a 64-bit integer, while `size_t` is 32 bit

The correct format specification for `size_t` is `%zu`. For `ssize_t` it is `%zd`. Pull requests are messy, so I'll just leave an old-fashioned patch-file here. Please, merge it in. Thank you!

[patch-warnings](https://github.com/dropbox/lepton/files/365107/patch-warnings.txt)

**Comment by danielrh** [comment]
Hmm... is %zu standard on all compilers--even weird ones like MSVC?
http://stackoverflow.com/questions/15610053/correct-printf-format-specifier-for-size-t-zu-or-iu
it seems not...
I just casted them to longs and used %lu for now
