### ISSUE TITLE
Test_Invariants Build Failure

### ISSUE THREAD

**Issue by tatoalo** [dropbox/lepton#12]
I've tested on a Windows 10 VM running Ubuntu 16.04 LTS.
During the build process I fail to pass the test_invariants, I then looked into the log file and saw this:

`mmap: Cannot allocate memory`
`Insufficient memory: unable to mmap or calloc 1006633216 bytes`
`FAIL test_suite/test_invariants (exit status: 37)`

I don't understand why a calloc would have failed since I really doubt I don't have enough contiguous memory available.

Thanks,
Alessandro

**Comment by danielrh** [comment]
maybe it has to do with how your VM is setup? I can't reproduce the issue.
It tries to allocate a gig of memory for some of the tests... 

the test_invariants test doesn't do much--- basically it just checks division and a few things-- we could probably lower the memory requirement

is that the only test that fails?

**Comment by tatoalo** [comment]
Yes, it's the only one that fails.
(My VM setup has 4 GBs available as memory)

**Comment by chrisjwatts** [comment]
Hey Daniel,

I think this is the same error, below is one of the sections.

I'm running this on a small 2GB with 4GB Swap Digital Ocean VPS.. Is this to small?

Thanks in advanced

# TOTAL: 39
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  29
# XPASS: 0
# ERROR: 0
 -------------------------
Loading 2670607
./lepton -hugepages -decode -recodememory=24M - (NULL)
Huge pages unsupported: falling back to ordinary pages
mmap: Cannot allocate memory
Insufficient memory: unable to mmap or calloc 1073742336 bytes
./lepton -hugepages -recode -recodememory=24M - (NULL)
Huge pages unsupported: falling back to ordinary pages
mmap: Cannot allocate memory
Insufficient memory: unable to mmap or calloc 1073742336 bytes
FAIL test_suite/test_phone_outdoor (exit status: 141)
