### ISSUE TITLE
Can you give some description about lepton file form for understanding the code

### ISSUE THREAD

**Issue by mychaow** [dropbox/lepton#126]
I am not familiar with encode/decode algorithm of image, so when I read the code, I feel very confused.  Can you give some description about the lepton file form to help me understand the code?  I want to know: how to split jpeg to segment, the relationship between segement and chunk,  and so on.    Thank you!

**Comment by danielrh** [comment]
https://www.usenix.org/system/files/conference/nsdi17/nsdi17-horn-daniel.pdf
Appendix A has some information about the file format and how to parse apart the sections
