### ISSUE TITLE
I feel confuse about "UJPG" in the code...What does it mean?

### ISSUE THREAD

**Issue by xiaoxiongli** [dropbox/lepton#128]
I feel confuse about "UJPG" in the code...,   it seems that "UJPG" stand for "uncompressed JPEG", but what does "uncompressed JPEG" stand for?  it meas YCbCr data or something else?

**Comment by xiaoxiongli** [comment]
Dear @danielrh , Please help ... ^_^, i feel confuse about it, thank you very much

**Comment by danielrh** [comment]
The idea is that the JPEG has been uncompressed into its frequency space components but the header is persisted in a uniform way. This was largely used to test lepton's (and uncmpJPG's https://github.com/packjpg/JPEG-Developers-Package ) ability to roundtrip jpeg files
