### ISSUE TITLE
how to improve the compression rate?

### ISSUE THREAD

**Issue by xiaoxiongli** [dropbox/lepton#130]
Dear @danielrh:

Could you please give me some ideas which can impoving the lepton's compression rate?  such as more accurate predicted coef or something else to impove compression rate.  

thank you very much! ^_^

**Comment by danielrh** [comment]
If I recall correctly, right now 1x7 and 7x1 vectors use the Lakhani transform to help inform the prior bucket index for the 1x7 and 7x1. I better solution would be to subtract the Lakhani prediction from the actual value and encode the delta only.  I never quite got the math to work out such that it would deliver better compression, but I imagine it might do nicely. A similar approach might be applied to DC
more information can be seen in  A.2.2 and A.2.3 of the paper https://arxiv.org/pdf/1704.06192.pdf
