### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Terricide** [dropbox/lepton#17]
Are there any plans for a javascript decoder?

**Comment by alamcordeiro** [comment]
similar to this
http://libwebpjs.appspot.com

**Comment by greggmojica** [comment]
+1

**Comment by pinceladasdaweb** [comment]
+1

**Comment by amitkanfer** [comment]
+1

**Comment by danielrh** [comment]
It does build with the incoming version of emscripten
it *may* run with -skipverify compiler flag and -singlethread turned on... I don't have time to check

**Comment by danielrh** [comment]
This branch has significant progress along that path 
https://github.com/dropbox/lepton/tree/emscripten
Feel free to play with it and help us develop it further :-)

**Comment by danielrh** [comment]
merged into master
