### ISSUE TITLE
Progressive images - Usage to be documented

### ISSUE THREAD

**Issue by prabindh** [dropbox/lepton#22]
For progressive images, if -allowprogressive is not explicitly added in commandline, will throw error 

"
lepton v1.0-
Failed To start subprocess with command line OS_ERROR
"

Works fine with -allowprogressive option.
- Appropriate error has to be thrown (Minor fix)
- Check can be added in code and the right code path taken without returning error.

Platform : Win10, Visual Studio 14 2015

**Comment by danielrh** [comment]
it's a good question-- I suppose we could add a build directive to do this.

-allowprogressive is simply an inconvenience flag... it just exits if it sees allowprogressive...
there's no harm to always specify the flag: it will branch to the right code path

At Dropbox we don't want to allow progressive to guarantee that the fastpath code is always run and that the memory usage doesn't balloon for decompression. One day we may turn it on, but it's easier to be less permissive to start with and slowly open the floodgates.

**Comment by danielrh** [comment]
I added a different header number for progressive images: this will let the decoder know which mode to go into... That way you can always specify allowprogressive and it will decode ok.

**Comment by prabindh** [comment]
Perfect. Thanks.
