### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [dropbox/lepton#37]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [fork_serve](https://github.com/dropbox/lepton/blob/57801dd796a501f007b708f7fbf90a3572b0f17a/src/lepton/fork_serve.cc#L75)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html) ⇒ [socket_serve](https://github.com/dropbox/lepton/blob/f1eec6339861004d2f47dcb1b467c4889f6f5587/src/lepton/socket_serve.cc#L306)

**Comment by danielrh** [comment]
fprintf is for logging and the signal handlers are pretty optional.
I've added a bit in this diff 37bfaaf18d3605f28f725f31b83040b1888be510

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for [your software](https://github.com/dropbox/lepton/blob/37bfaaf18d3605f28f725f31b83040b1888be510/src/lepton/fork_serve.cc#L78 "Update candidate: fork_serve()")?
