### ISSUE TITLE
Inconsistency between autoreconf and CMake

### ISSUE THREAD

**Issue by Maxime-J** [dropbox/lepton#38]
I discover CMake with this project and it seems to be a great tool.
However, providing both autoreconf and CMake way makes it a little hard to understand the build logic, especially because there's inconsistency between the two.

On the same linux system, CMake and autoreconf will not set the same compiler flags (With CMake: static, msse4.2 ... and with autoreconf: mssse3 ... ).
CMake also adds the avx target.

Shouldn't it be better to maintain only the CMake version?

**Comment by danielrh** [comment]
most distros like to package the ./configure...
also someone would need to port over the test suite to cmake

**Comment by Maxime-J** [comment]
Ok, thanks for the answer.
I close the issue as it's not really important and I mostly wanted to point out the fact that CMake isn't the exact port of ./configure.
