### ISSUE TITLE
Assertion failure on truncated file

### ISSUE THREAD

**Issue by TheLoneWolfling** [dropbox/lepton#4]
The following file: [crash.zip](https://github.com/dropbox/lepton/files/364615/crash.zip) (or rather, the file inside said archive, as Github won't allow me to upload it directly), causes an assertion failure on default settings on my machine:

```
lepton v1.0-a34ee2f
lepton: src/lepton/bitops.cc:459: unsigned int ibytestream::read(unsigned char*, unsigned int): Assertion `size' failed.
```

(Alternatively, a hexdump of said file is `d8ff 30ff 0200`)

**Comment by TheLoneWolfling** [comment]
Actually: is this something you care about?

**Comment by danielrh** [comment]
We actually only care about jpegs that make it all the way to the SOS markers :-)
Generic compression (eg brotli) takes care of the header pretty well, so if there's no scan, then there are better ways to get compression.

That said, if you can come up with a patch that accepts these kinds of files, we'd be happy to merge it in.

**Comment by TheLoneWolfling** [comment]
> We actually only care about jpegs that make it all the way to the SOS markers :-)

Is that just for assertions, or just a flat-out don't care?

Or, to put it another way, do you care about invalid files causing segfaults / div by 0s / etc?
