### ISSUE TITLE
Unable to build on Win7

### ISSUE THREAD

**Issue by jcoady9** [dropbox/lepton#40]
When I try to build the solution in visual studio it throws me numerous instances of the below error:

error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   ..\lepton\src\vp8\util\memory.cc

as well as:

Error   116 error C3867: 'UncompressedComponents::header_': function call missing argument list; use '&UncompressedComponents::header_' to create a pointer to member   ..\lepton\src\lepton\uncompressed_components.hh      line 175

I'm building v1.0 from commit 911d79a560c303a2a62e5412117d0a4ccb41836d

**Comment by danielrh** [comment]
Can you try version 1.2?
Those look like errors we fixed

Also is this visual studio 2014? What version?

**Comment by jcoady9** [comment]
I just tried version 1.2.1 on visual studio 2013 and it gives me the same errors.

**Comment by danielrh** [comment]
You need visual studio 2014...it's free but requires Win8
mingw should also work

**Comment by danielrh** [comment]
If you paste the entire log there's a chance we can find workarounds--but fundamentally this is a C++11 project, so it's likely there are going to be missing features like std::thread

**Comment by dawjan** [comment]
9Gb visual studio 2014, no spaces on my SSD.
Can you just make binary :)
