### ISSUE TITLE
 A process left after running unit test

### ISSUE THREAD

**Issue by czchen** [dropbox/lepton#42]
It is from Debian bug report [#831897](https://bugs.debian.org/831897). After running unit test, the following process is in system.

```
% ps auxww | grep lepton
czchen    9926  0.0  0.0 1328568 3620 pts/4    S    10:55   0:00 ./lepton -socket=/tmp/876b9068-b337-469d-b7ce-e31456b5b634 -timebound=10ms -preload
```

**Comment by danielrh** [comment]
oh fascinating! good to know...  that's probably a bug in https://github.com/dropbox/lepton/blob/master/test_suite/sockettester.py
