### ISSUE TITLE
Output format stability

### ISSUE THREAD

**Issue by pstibrany** [dropbox/lepton#43]
Is the lepton output format stable? For example packJPG says "Compressed PJG files are not compatible between different packJPG versions." What is the status in lepton? Can this be documented in README please?

Thanks.

**Comment by danielrh** [comment]
We definitely will need for newer versions to be able to decode older data, since we have a lot of data that has already been encoded.
We may choose to add features and provide a way for the decoder to understand both versions.
Old decoders may not understand new versions of lepton

**Comment by romiras** [comment]
You can choose RIFF (or even RF64) as container, similarly as WebP uses it.

**Comment by danielrh** [comment]
The current format has versioning and some feature flags builtin... I think it should be fine to keep it. There's really no value in adding things like metadata into lepton. Lepton is supposed to merely reflect the original file with as little room for creativity as possible.

**Comment by pstibrany** [comment]
I'm perfectly happy to use whatever format you think is the best, as long as lepton can decode it back bit-to-bit to original file :) Thanks for explaining your thinking behind format versions compatibility.
