### ISSUE TITLE
jpegoptim

### ISSUE THREAD

**Issue by tallesl** [dropbox/lepton#44]
Hi,

Do you guys have any benchmarks or comments on this tool versus [jpegoptim]?

[jpegoptim]: https://github.com/tjko/jpegoptim

**Comment by danielrh** [comment]
Yes: jpegopt saves between 5 and 10 percent, and from our initial benchmark takes several hundred milliseconds where lepton saves 22% and takes 60 ms on average for a representative set of images.
Will release the data once we've finished analyzing it and chewing through it...these numbers are preliminary at best

The advantage with jpegotim is that you get a jpeg out
the disadvantage is that it usually doesn't return the original bit-for-bit, so it's hard to tell if the compression system is reliable or not
