### ISSUE TITLE
Listen server hangs on OS X

### ISSUE THREAD

**Issue by MattFlower** [dropbox/lepton#50]
From the current master in github.com, I clone master and cd into that directory.  In one terminal I start lepton with:

    ./lepton -listen=2020

In a second terminal, I run:

    cat images/iphone.jpg | netcat localhost 2020

On my linux virtual machine, this works exactly as expected - binary compressed data is written to stdout.  On mac it hangs at jpgcoder.cc:1532 while consuming input:

    $ ./lepton -listen=2020
    /tmp/e4a49584aa-2616-b410-c273f5cf602a-2c.uport
    START ACHIEVED 1469565561 607237

It will sit there indefinitely until you ctrl-c the window running netcat.  Then you'll see the output window print a bunch of output, seemingly indicating that it is processing the file.

    <many lines...>
    TS_DONE	(0)	35.022779
    12133028 bytes needed to decompress this file
    DONE
    Child 60631 exited with signal 13

I've attached the full output log from the server.  Any help you can provide would be great.

[log.txt](https://github.com/dropbox/lepton/files/384752/log.txt)

**Comment by danielrh** [comment]
Hmm I encountered the issue once when OS X was using poll instead of select... I had a dtruss session open and it really seemed that the message was missed

I'm not sure what's going on... is this repeatable?

**Comment by MattFlower** [comment]
Completely - I've tried several times, thinking I was doing something wrong. I also wrote a Java program that reproduces it on my Mac, though I haven't tried running that program in Linux to confirm that it works without error there. 

Let me try running it on another mac to see if it has the same behavior. I don't believe I have anything running that should impact my network like dtruss might, but let me see what I can do to eliminate that possibility.

**Comment by Tremelune** [comment]
Same on my machine (OS X 10.11.3). When the process is manually terminated, it appears to then complete successfully.

**Comment by MattFlower** [comment]
I believe I have figured it out.  There are two, maybe three implementations of bsd in play.  There is the original one by hobbit, a "gnu-branded" one, and the bsd rewrite of netcat.  The original hobbit one and the gnu one don't seem to work.  The bsd one does work.

You can install the netcat-traditional on ubuntu and you'll have the same problem I was having on mac.

I suspect that underlying cause is the sending of FIN on the socket from client to server when the data is done being sent.  I don't think the gnu and hobbit netcat's are sending it.  The server cannot know that the data is done, so it hangs out waiting.  I figured this out when I noticed that I had the same bug in my own code -- I had failed to send FIN.  If anyone happens to be using Java and reading this, don't forget to call Socket.shutdownInput() when you are done sending your image.

I think this bug can be closed out.  It's user (me) error in the end.
