### ISSUE TITLE
C++11 requires a space between literal and identifier

### ISSUE THREAD

**Issue by pgurumukhi** [dropbox/lepton#53]
Getting below error while running command: make or make -j8 on Amazon Linux x86_64-redhat-linux
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)
Please help.

src/lepton/jpgcoder.cc:52:27: fatal error: linux/seccomp.h: No such file or directory
 #include <linux/seccomp.h>
                           ^
compilation terminated.
src/lepton/vp8_encoder.cc:52:52: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
                                   case SIGN8:nam = "SI#include "emmintrin.h"GN8";break;
                                                    ^
make[1]: *** [src/lepton/jpgcoder.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/mnt/pankajg/lepton'
make: *** [all] Error 2

**Comment by danielrh** [comment]
it almost seems like your download is corrupted.
How did you get the source? Did you download the 1.2 release? Did you check things out with git?

**Comment by danielrh** [comment]
Closing for now: cannot repro.
Feel free to post information and reopen
