### ISSUE TITLE
Question with big images

### ISSUE THREAD

**Issue by jumbi77** [dropbox/lepton#58]
Hi,
when i want to compress a big JPG (around [54MB](http://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x21600x21600.A1.jpg)) with no tuning settings i get the following result but no 'a.lep' file:

> ./lepton a.jpg a.lep
> lepton v1.0-
> START ACHIEVED 1470607045 175695
> OOM
> SHORT_READ

I have to set the -memory up to 3GB to get it working, is that correct?
(using OSX, installed with brew). Would be nice if lepton decides for themselves how much memory is required to compress the image.

> ./lepton -memory=3072M a.jpg a.lep
> lepton v1.0-
> START ACHIEVED 1470607052 506527
> TS_MAIN   (0) 0.000000
> TS_MODEL_INIT_BEGIN   (0) 10.512067
> TS_MODEL_INIT_BEGIN   (1) 10.412967
> TS_MODEL_INIT_BEGIN   (2) 10.413010
> TS_MODEL_INIT_BEGIN   (3) 10.413037
> TS_MODEL_INIT_BEGIN   (4) 10.413102
> TS_MODEL_INIT_BEGIN   (5) 10.432212
> TS_MODEL_INIT_BEGIN   (6) 10.479795
> TS_MODEL_INIT_BEGIN   (7) 10.487485
> TS_MODEL_INIT (0) 10.516036
> TS_MODEL_INIT (1) 10.418249
> TS_MODEL_INIT (2) 10.421953
> TS_MODEL_INIT (3) 10.416062
> TS_MODEL_INIT (4) 10.417307
> TS_MODEL_INIT (5) 10.433794
> TS_MODEL_INIT (6) 10.481520
> TS_MODEL_INIT (7) 10.490361
> TS_THREAD_STARTED (0) 0.001805
> TS_READ_STARTED   (0) 0.001858
> TS_READ_FINISHED  (0) 0.987120
> TS_JPEG_DECODE_STARTED    (0) 0.987120
> TS_JPEG_DECODE_FINISHED   (0) 10.397602
> TS_STREAM_MULTIPLEX_STARTED   (0) 27.475147
> TS_STREAM_MULTIPLEX_FINISHED  (0) 27.787765
> TS_THREAD_WAIT_STARTED    (1) 26.034472
> TS_THREAD_WAIT_STARTED    (2) 26.034480
> TS_THREAD_WAIT_STARTED    (3) 26.034482
> TS_THREAD_WAIT_STARTED    (4) 26.034483
> TS_THREAD_WAIT_STARTED    (5) 26.034486
> TS_THREAD_WAIT_STARTED    (6) 26.034487
> TS_THREAD_WAIT_STARTED    (7) 26.034489
> TS_THREAD_WAIT_FINISHED   (1) 26.034480
> TS_THREAD_WAIT_FINISHED   (2) 26.034482
> TS_THREAD_WAIT_FINISHED   (3) 26.034483
> TS_THREAD_WAIT_FINISHED   (4) 26.034486
> TS_THREAD_WAIT_FINISHED   (5) 26.034487
> TS_THREAD_WAIT_FINISHED   (6) 26.034489
> TS_THREAD_WAIT_FINISHED   (7) 27.475146
> TS_ARITH_STARTED  (0) 10.512066
> TS_ARITH_STARTED  (1) 10.412967
> TS_ARITH_STARTED  (2) 10.413009
> TS_ARITH_STARTED  (3) 10.413037
> TS_ARITH_STARTED  (4) 10.413102
> TS_ARITH_STARTED  (5) 10.432212
> TS_ARITH_STARTED  (6) 10.479794
> TS_ARITH_STARTED  (7) 10.487484
> TS_ARITH_FINISHED (0) 26.034472
> TS_ARITH_FINISHED (1) 23.823887
> TS_ARITH_FINISHED (2) 22.709831
> TS_ARITH_FINISHED (3) 23.167249
> TS_ARITH_FINISHED (4) 24.222650
> TS_ARITH_FINISHED (5) 24.642485
> TS_ARITH_FINISHED (6) 25.132216
> TS_ARITH_FINISHED (7) 27.475085
> TS_STREAM_FLUSH_STARTED   (0) 27.787765
> TS_STREAM_FLUSH_FINISHED  (0) 27.787767
> TS_DONE   (0) 27.787819
> 77233505 bytes needed to decompress this file
> 37811888 54085715
> 69.91%
> START ACHIEVED 1470607080 541507
> TIMING (new method): 18.372288 to first byte 18.372288 total
> Read took: 0.000197
> TS_MAIN   (0) 0.000000
> TS_MODEL_INIT_BEGIN   (0) 28.143415
> TS_MODEL_INIT_BEGIN   (1) 28.143373
> TS_MODEL_INIT_BEGIN   (2) 28.143380
> TS_MODEL_INIT_BEGIN   (3) 28.143389
> TS_MODEL_INIT_BEGIN   (4) 28.146351
> TS_MODEL_INIT_BEGIN   (5) 28.150565
> TS_MODEL_INIT_BEGIN   (6) 28.150580
> TS_MODEL_INIT_BEGIN   (7) 28.158941
> TS_MODEL_INIT (0) 28.149988
> TS_MODEL_INIT (1) 28.145129
> TS_MODEL_INIT (2) 28.145243
> TS_MODEL_INIT (3) 28.145077
> TS_MODEL_INIT (4) 28.148581
> TS_MODEL_INIT (5) 28.151989
> TS_MODEL_INIT (6) 28.165408
> TS_MODEL_INIT (7) 28.160659
> TS_THREAD_STARTED (0) 28.036782
> TS_READ_STARTED   (0) 28.036851
> TS_READ_FINISHED  (0) 28.037023
> TS_STREAM_MULTIPLEX_STARTED   (0) 28.143414
> TS_STREAM_MULTIPLEX_STARTED   (1) 28.143372
> TS_STREAM_MULTIPLEX_STARTED   (2) 28.143380
> TS_STREAM_MULTIPLEX_STARTED   (3) 28.143389
> TS_STREAM_MULTIPLEX_STARTED   (4) 28.146351
> TS_STREAM_MULTIPLEX_STARTED   (5) 28.150565
> TS_STREAM_MULTIPLEX_STARTED   (6) 28.150580
> TS_STREAM_MULTIPLEX_STARTED   (7) 28.158940
> TS_STREAM_MULTIPLEX_FINISHED  (0) 28.150405
> TS_STREAM_MULTIPLEX_FINISHED  (1) 28.145878
> TS_STREAM_MULTIPLEX_FINISHED  (2) 28.145659
> TS_STREAM_MULTIPLEX_FINISHED  (3) 28.145555
> TS_STREAM_MULTIPLEX_FINISHED  (4) 28.148985
> TS_STREAM_MULTIPLEX_FINISHED  (5) 28.152365
> TS_STREAM_MULTIPLEX_FINISHED  (6) 28.165804
> TS_STREAM_MULTIPLEX_FINISHED  (7) 28.161039
> TS_THREAD_WAIT_STARTED    (1) 44.732890
> TS_THREAD_WAIT_STARTED    (2) 44.758106
> TS_THREAD_WAIT_STARTED    (3) 44.783672
> TS_THREAD_WAIT_STARTED    (4) 44.809829
> TS_THREAD_WAIT_STARTED    (5) 44.834752
> TS_THREAD_WAIT_STARTED    (6) 44.859716
> TS_THREAD_WAIT_STARTED    (7) 44.883532
> TS_THREAD_WAIT_FINISHED   (1) 44.732898
> TS_THREAD_WAIT_FINISHED   (2) 44.758110
> TS_THREAD_WAIT_FINISHED   (3) 44.783676
> TS_THREAD_WAIT_FINISHED   (4) 44.809833
> TS_THREAD_WAIT_FINISHED   (5) 44.834755
> TS_THREAD_WAIT_FINISHED   (6) 44.859720
> TS_THREAD_WAIT_FINISHED   (7) 46.382081
> TS_ARITH_STARTED  (0) 28.143414
> TS_ARITH_STARTED  (1) 28.143371
> TS_ARITH_STARTED  (2) 28.143380
> TS_ARITH_STARTED  (3) 28.143389
> TS_ARITH_STARTED  (4) 28.146350
> TS_ARITH_STARTED  (5) 28.150564
> TS_ARITH_STARTED  (6) 28.150579
> TS_ARITH_STARTED  (7) 28.158939
> TS_ARITH_FINISHED (0) 44.732889
> TS_ARITH_FINISHED (1) 42.568798
> TS_ARITH_FINISHED (2) 41.561109
> TS_ARITH_FINISHED (3) 42.013757
> TS_ARITH_FINISHED (4) 43.175662
> TS_ARITH_FINISHED (5) 43.604729
> TS_ARITH_FINISHED (6) 44.189564
> TS_ARITH_FINISHED (7) 46.382012
> TS_JPEG_RECODE_STARTED    (0) 44.732889
> TS_JPEG_RECODE_STARTED    (1) 44.732898
> TS_JPEG_RECODE_STARTED    (2) 44.758110
> TS_JPEG_RECODE_STARTED    (3) 44.783676
> TS_JPEG_RECODE_STARTED    (4) 44.809833
> TS_JPEG_RECODE_STARTED    (5) 44.834755
> TS_JPEG_RECODE_STARTED    (6) 44.859720
> TS_JPEG_RECODE_STARTED    (7) 46.382081
> TS_JPEG_RECODE_FINISHED   (0) 46.409170
> TS_JPEG_RECODE_FINISHED   (1) 44.758106
> TS_JPEG_RECODE_FINISHED   (2) 44.783672
> TS_JPEG_RECODE_FINISHED   (3) 44.809829
> TS_JPEG_RECODE_FINISHED   (4) 44.834752
> TS_JPEG_RECODE_FINISHED   (5) 44.859716
> TS_JPEG_RECODE_FINISHED   (6) 44.883531
> TS_JPEG_RECODE_FINISHED   (7) 46.409054
> TS_DONE   (0) 46.409178
> 149788324 bytes needed to decompress this file
> 37811888 54085715
> 69.91%

**Comment by danielrh** [comment]
It would be pretty easy to put lepton by default into an "unconstrained" mode where it used the system allocator-- maybe next version since there are a few bug reports about this

**Comment by danielrh** [comment]
Strangely your build is also running a bunch of redundant checks, probably running at 1/3 speed or less. It seems that the brew build forgot to enable -DNDEBUG

**Comment by danielrh** [comment]
This is now the default on master.
I'll cut a new release in a week or two
