### ISSUE TITLE
"version" make target needs to be a dependency

### ISSUE THREAD

**Issue by bobobo1618** [dropbox/lepton#63]
Steps to reproduce:
- `git clone`
- `mkdir build`
- `cd build`
- `cmake -DCMAKE_BUILD_TYPE=release -DUSE_SYSTEM_DEPENDENCIES=ON -DCMAKE_INSTALL_PREFIX="/usr" ..`
- `make`

Actual result:

```
[ 11%] Building CXX object CMakeFiles/lepton-avx.dir/src/lepton/jpgcoder.cc.o
/home/me/lepton/src/lepton/src/lepton/jpgcoder.cc:80:22: fatal error: version.hh: No such file or directory
 #include "version.hh"
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/lepton-avx.dir/build.make:159: CMakeFiles/lepton-avx.dir/src/lepton/jpgcoder.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/lepton-avx.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Expected result: Completed build

Simply running `make version` before running `make` results in a proper build.

**Comment by danielrh** [comment]
mind making a pull request for this? My cmake is a bit rusty

**Comment by bobobo1618** [comment]
I haven't the faintest idea how I'm afraid. I've never written much CMake.

**Comment by danielrh** [comment]
I think this is resolved: closing for now...
reopen if it's still causing issues
