### ISSUE TITLE
Some JPEG files become even larger after lepton compression

### ISSUE THREAD

**Issue by sp-1234** [dropbox/lepton#64]
Example: https://cloud.githubusercontent.com/assets/1442206/17919118/005ee04c-69dc-11e6-83e0-4d027edfb399.jpg

It gives 102% (bigger file)

**Comment by danielrh** [comment]
With lossless compression, by the pigeon hole principle, if some files can compress smaller then others, necessarily, must be bigger

here's a more detailed explanation
http://web.stanford.edu/class/archive/cs/cs103/cs103.1132/lectures/08/Small08.pdf

**Comment by magicgoose** [comment]
but it can store uncompressable data literally, like does LZMA2 for example, right?
