### ISSUE TITLE
(error) Using 'memset' on struct that contains a 'std::vector'

### ISSUE THREAD

**Issue by bryongloden** [dropbox/lepton#66]
Greetings. I found three issues, where `memset` is used on a struct that contains a `std::vector`. This can be dangerous and can lead to inconsistent memory (see discussion at http://stackoverflow.com/questions/6877281/memset-structure-with-stdstring-contained).

```
[src/vp8/util/block_context.hh:92]: (error) Using 'memset' on struct that contains a 'std::vector'.
[src/vp8/util/block_context.hh:100]: (error) Using 'memset' on struct that contains a 'std::vector'.
[src/vp8/util/block_context.hh:123]: (error) Using 'memset' on struct that contains a 'std::vector'.
```

Found by https://github.com/bryongloden/cppcheck

**Comment by danielrh** [comment]
in this case it's std::vector<>::iterator
so most compilers will represent it as a pointer... for which NULL won't cause memory corruption

That said: it's correctly identified as undefined behavior and I've got a patch to fix it... coming soon

**Comment by bryongloden** [comment]
Thanks for correcting my typo 👍
And way to go (WTG) with your patch!
