### ISSUE TITLE
How to get 5MB/s encode rate?

### ISSUE THREAD

**Issue by Ryen** [dropbox/lepton#68]
I am testing on Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, using the sockettester.py. But only get 1.2MB/s for many jpgs.  Is there any trick or argument I need to set to make it faster?

**Comment by pstibrany** [comment]
Maybe your binary is built with debug flag turned on? I had similar problem in issue #55

**Comment by Ryen** [comment]
Er, I just build using 
```
./autogen.sh
./configure
make
```
Is there any flag to set it? And I've seen there is an avx2 version, how to build it? 
Thanks!

**Comment by danielrh** [comment]
make sure to pass
``` 
./autogen.sh
CXXFLAGS="-O3 -DNDEBUG" ./configure
make
```
or you can do 
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Release
make

also try passing -noverify as well... though I would recommend that you also verify it yourself

**Comment by Ryen** [comment]
Thanks, use -O3 flag really works~
