### ISSUE TITLE
Lepton version doesn't show properly

### ISSUE THREAD

**Issue by C0rn3j** [dropbox/lepton#80]
Using package from [AUR](https://aur.archlinux.org/packages/lepton/) (Which likely isn't an issue, PKGBUILD doesn't seem to do anything with the version).

 c0rn3j@c0rn3jDesktop  ~  lepton
lepton v1.0-

 ✘ c0rn3j@c0rn3jDesktop  ~  lepton -version
01

I'd imagine it'd show 1.2.1 somewhere?

**Comment by danielrh** [comment]
right now the version 1.0 is more centered around the file format version. I think if you actually run a conversion it shows the git hash or a properly built package hash?
which apparently wasn't set for that package build....if you look at the packages in the release here I believe the version is actually computed this way using cmake

```     COMMAND ${GIT_EXECUTABLE} --git-dir=${PROJECT_SOURCE_DIR}/.git --work-tree\
=${PROJECT_SOURCE_DIR} rev-parse HEAD                                           
     OUTPUT_VARIABLE VERSION                                                    
     OUTPUT_STRIP_TRAILING_WHITESPACE  ```

and this way 
```-DGIT_REVISION=\"$(shell git describe --dirty --always 2> /dev/null || basename `pwd`)\"```
using configure
