### ISSUE TITLE
Help me / How I can compile this projects in Visual Studio

### ISSUE THREAD

**Issue by bogdanbogaychuk** [dropbox/lepton#92]

**Comment by danielrh** [comment]
Download cmake
https://cmake.org/download/
```
mkdir build
cd build
"c:\Program Files\CMake\bin\cmake.exe -G "Visual Studio 14 2015" ..
```
that should generate a .sln file in your current directory
then you can build it

**Comment by bogdanbogaychuk** [comment]
how to extract compressed file "lep" images but for it to be compressed and
not returned to its original state?

2017-05-16 12:01 GMT+03:00 Daniel <notifications@github.com>:

**Comment by bogdanbogaychuk** [comment]
or immediately compress the file size, I can not extract the compressed
image with "lip" file

2017-05-17 14:16 GMT+03:00 Богдан Богайчук <bgamer.infini@gmail.com>:
