### ISSUE TITLE
prctl(SECCOMP): Invalid argument

### ISSUE THREAD

**Issue by Dingo64** [dropbox/lepton#94]
Hello!
I compiled lepton under Debian 8.8 amd64. It shows version information or help info just fine but when I try to compress a file:
` ./lepton -singlethread ../test.jpg test.lep`
I get:
```
lepton v1.0-1.2.1-102-g4d14fe2
prctl(SECCOMP): Invalid argument
SHORT_READ
```
How can I fix this?

**Comment by Dingo64** [comment]
When I compile:
`https://github.com/dropbox/lepton/archive/1.2.tar.gz`
I get this:
```
lepton v1.0-lepton-1.2
prctl(SECCOMP): Invalid argument
SECCOMP_MODE_STRICT is not available.
Trying to set a filter to emulate strict mode
prctl(SECCOMP): Invalid argument
SHORT_READ

```

**Comment by danielrh** [comment]
can you try running with -unjailed to see if that helps (only use trusted content with that option--but it should help us diagnose the issue)

Can you also try checking out the latest source code from master--I made the seccomp stuff a little more permissive when playing around with a ibm power system?

**Comment by Dingo64** [comment]
Sorry, I made a mistake. I compiled under Debian 8.8 amd64 but mistakenly tested on Debian 8.5 amd 64. The error is from Debian 8.5. With -unjailed I get something similar:
```
START ACHIEVED 1495455159 210117
SHORT_READ
Illegal instruction
```
It does work on Debian 8.8 just fine. But is there any chance to compile in a way that allows me to use it on Debian 8.5 too? I can't compile it there.

**Comment by danielrh** [comment]
it sounds possible that the -march=native causes the issue
if you build with cmake then you should get out a version that works

cd build
cmake ..
make -j8
I think lepton or lepton-scalar should work on your 8.5 system
lepton-avx may not (due to requiring core-avx2)
Hope that helps
