### ISSUE TITLE
`make check` failures on test_legacy.sh and test_16threads.sh

### ISSUE THREAD

**Issue by sjuxax** [dropbox/lepton#95]
I get failures on two tests when I run `make check`: `test_legacy` and `test_16threads`.

Compiling on an up-to-date ArchLinux. Tried with `make -j16` first and retried with `make -j1` with no change. Built off today's HEAD.

```
$ git rev-parse HEAD
26901e5078876f42bbbfbf3b0fe6bcbe81f787ee
```
```
$ g++ --version
g++ (GCC) 7.1.1 20170516
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
`CXXFLAGS` (`CFLAGS` are identical)
```
$ echo $CXXFLAGS
-march=native -mtune=native -O2 -pipe -fstack-protector-strong -mavx2
```
```
$ uname -a
Linux kvm_master 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
```

Found a similar bug report on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853479

[lepton-test-suite.log.txt](https://github.com/dropbox/lepton/files/1083403/lepton-test-suite.log.txt)
[lepton_build.stdout.log.txt](https://github.com/dropbox/lepton/files/1083416/lepton_build.stdout.log.txt)
[lepton_build.stderr.log.txt](https://github.com/dropbox/lepton/files/1083415/lepton_build.stderr.log.txt)

**Comment by danielrh** [comment]
Turns out it's a gcc bug
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81015
bad codegen for builtin_clz
will avoid using that for gcc 7 series... 
that's really scary
